sasaki77/archiverappliance-datasource

package.json, src/DataSource.ts, src/specs/aafunc.test.ts, src/specs/datasource.test.ts
In raw operator mode, an archived data might be cut off at last archived time or not be displayed.
This pull request adds extrapolation feature in raw operator mode.
=> Add extrapolation for raw operator

src/DataSource.ts, src/specs/aafunc.test.ts, src/specs/datasource.test.ts, src/types.ts
This PR changes retrieving data format from `json` to `qw`.
`qw` format has timestamp as milli seconds while `json` format has timestamp with secs and nanos.
`qw` format allows to remove conversion from secs and nanos to milli seconds.
=> Change retrieving data format from json to qw

src/DataSource.ts, src/specs/datasource.test.ts, src/types.ts
This PR adds support for array data.
Array data is handled as [wide format data frame](https://grafana.com/docs/grafana/latest/developers/plugins/data-frames/#wide-format).
Field name for each array element becomes like `PVNAME[0]` while the field name for a scalar value is `value`.
Supporting alias for array data is also included in this PR.
=> Support array data

package.json, src/DataSource.ts, src/aafunc.ts, src/components/FunctionElem.test.tsx, src/components/FunctionParams.test.tsx, src/components/Functions.tsx, src/components/__snapshots__/FunctionAdd.test.tsx.snap, src/components/__snapshots__/FunctionElem.test.tsx.snap, src/dataProcessor.ts, src/specs/aafunc.test.ts, src/types.ts, yarn.lock
This PR adds `Array to Scalar` functions.
`Array to Scalar` functions allows to transform array data into scalar data with some method.
This PR includes the functions as below.
-  toScalarByAvg
-  toScalarByMax
-  toScalarByMin
-  toScalarBySum
-  toScalarByMed
-  toScalarByStd
=> Add Array to Scalar functions

src/components/FunctionParam.tsx
This PR fixes function parameter width during focusing on it.
The width is dynamically changed when the parameter length is more than default parameter width.
=> fix: Fix Function parm width during focusing on

.github/workflows/build-publish-docs.yml, .github/workflows/publish-release.yml, .gitignore, docs/requirements.txt
This PR adds documentation generation and posting to the `publish-release.yml` CI script. Documentation will be pushed to the `gh-pages` branch whenever a new tag is pushed to the GitHub repository. 
Discussion is welcome.
=> Automate documentation building on tags 

pkg/archiver-interface.go, pkg/archiver-query.go, pkg/archiver-query_test.go
This resolves the issue in which the all plots were displayed with the name "values" when using the back end data source exclusively.
=> BUG: properly name values

pkg/archiver-query.go, pkg/archiver-query_test.go, pkg/query-operators.go, pkg/query-operators_test.go, pkg/test_helpers.go
This PR closes #36. 
Only when using the backend for visualizations, the the backed will automatically apply the mean_# operator to reduce the volume of the data sent from the archiver. The size of the binning is based upon grafana's automatic bin sizing.
=> Reduce query size

pkg/archiver-query.go, pkg/archiver-query_test.go
Allows PVs of the form `prefix:(var:1|var:2|...|):intermediate:(a|b|...):suffix` to work properly with the backend and alerting. 
Closes #40
=> Resolves multi-variables bug

pkg/functions_test.go
This is to add a test for the fluctuation function for entries with only one data point. Given that the delta function experienced a bug with single-data-point sets, I thought it would make sense to check for it in the fluctuation function as well. Fortunately the bug does not exist there so I'm just adding the test by itself.
=> TST: add test for 1-length input to fluctutaion funciton

pkg/archiver-query.go, pkg/archiver-query_test.go
This PR implements @klauer's idea to allow non-regex PV's to handle enclosed parentheses like so:
```
(a(b|c)|d)e
```
Will be expanded to 
```
abe
ace
de
```
=> ENH: Recursive pv names

pkg/archiver-functions.go, pkg/archiver-interface.go, pkg/archiver-query.go, pkg/functions.go
Addresses #37. 
This makes the queries to the Archiver execute in parallel as opposed to serially. 
Should be merged after #41. Most of the diff shown in this PR is caused by an early merge I made in order to handle some incompatibilities between the two branches.
=> Parallel queries enhancement. 

pkg/archiver-query.go
Dataframe has FieldConfig that is optional display data for the field (e.g. unit, name over-ride, etc).
Legend name is shown as `"Dataframe name" "Field name"` by #60 PR. This means that the legend name is shown as `"PV name" "PV name"`.
This PR fixes the legend name as just `"PV name"`.
=> Backend: Add display name config to dataframe

src/components/FunctionAdd.tsx, src/components/__snapshots__/FunctionAdd.test.tsx.snap
This PR fix initial value of function add button. When a cascader button is opened, no function is selected every time.
`plus` icon is also added by this PR.
=> BUG: fix initial value of function add button

pkg/archiver-query.go
Fixes #75
This PR removes unnecessary parameters from QueryModel to fix "json: cannot unmarshal" error.
=> BUG: Fix "json: cannot unmarshal" error (#75)

pkg/functions.go, pkg/functions_test.go
Scale and Offset functions returned data without PV name.
This PR fixes this.
=> BUG: fix Scale and Offset functions to return data with PV name

pkg/archiver-query_test.go, pkg/query-operators.go, pkg/query-operators_test.go
Binning interval for operator should be determined by width of panel and time range.
Backend returned fixed 1 second binning interval when the operator is specified.
This PR fixes this.
=> BUG: (Backend) enable auto binning interval for specified operator

pkg/query.go, pkg/query_test.go
PV name isolation for syntax like "(PV:NAME:1|PV:NAME:2|...)" is always required even if regex is enabled, because AA sever doesn't support full regular expression.
This PR adds isolation before fetching PV names in regex mode.
=> BUG: fix backend regex mode to support alternation

pkg/aaclient_test.go, pkg/models.go, pkg/operators.go, pkg/operators_test.go, pkg/query.go, pkg/query_test.go
Data extrapolation should be enabled even if operator is not raw.
This PR fixes this.
=> BUG: enable extrapolation even if operator is not raw

src/DataSource.ts, src/aafunc.ts, src/components/__snapshots__/FunctionAdd.test.tsx.snap, src/specs/datasource.test.ts
This PR fixes #83.
`arrayFormat` function provides 3 types of array format: `timeseries`, `index`, and `dt-space`.
Assume that we have following array data:
```
[
{
"meta": {
"name": "PV:NAME",
"waveform": true,
"PREC": "0"
},
"data": [
{
"millis": 1577804410000,
"val": [
val1_1, val1_2, val1_3, val1_4, ..., val1_361
]
},
{
"millis": 1577804510000,
"val": [
val2_1, val2_2, val2_3, val2_4, ..., val2_361
]
}
]
}
]
```
Each format should return as following:
**timeseries**
| time          | PV:NAME[0] | PV:NAME[1] | ... | PV:NAME[360] |
| ------------- | -------- | -------- | -------- | -------- |
| 1577804410000 | val1_1 | val1_2 | ... | val1_361 |
| 1577804510000 | val2_1 | val2_2 | ... | val2_361 |
**index**
| index         | 2020-01-01T00:00:10.000Z   |2020-01-01T00:01:50.000Z   |
| …
=> ENH: add array format option function

pkg/archiverappliance/query.go, pkg/archiverappliance/query_test.go
Target pvname list should be unique. For example, query requires `PV:NAME(1|1)` then the Backend server returns only `[PV:NAME1]` not `[PV:NAME1, PV:NAME1]`.
=> BUG: (Backend) target pvname list should be unique

pkg/archiverappliance/pvparser.go, pkg/archiverappliance/pvparser_test.go
Query for `(a):(b):(c):(d|e)` should return `abcd` and `abce` PVs. However the backend returned `abce` and `abce`.
This PR fixes this problem.
=> BUG: alternative pattern doesn't work correctly

pkg/archiverappliance/aaclient.go, pkg/archiverappliance/aaclient_test.go, pkg/archiverappliance/query.go, pkg/archiverappliance/query_test.go, pkg/test_data/invalid_value_response.JSON
Archiver Appliance may return a response that contains `null` or `Infinity` values as follows.
```json
[ 
{ "meta": { "name": "PFRVA:NEG:2NDSYS:PLASM:RESIS" , "waveform": false , "EGU": "ohm" , "PREC": "0" },
"data": [ 
{ "millis": 1667786399401, "val": -Infinity },
{ "millis": 1667786401400, "val": null },
{ "millis": 1667786408400, "val": -Infinity },
{ "millis": 1667786409400, "val": null }] }
]
```
This PR fixes the plugin to return an error response in this case.
=> BUG: fix invalid response handling

pkg/archiverappliance/aaclient.go, pkg/archiverappliance/query.go, pkg/archiverappliance/query_test.go
The plugin returned a error response without frames if a response from AA has some error. Therefore, it couldn't return frames even if there are some acceptable responses on regex mode.
This PR fixes to return frames even if the response error occurs.
=> ENH: return frames even if a response error occurs

src/components/ConfigEditor.tsx, src/components/QueryEditor.tsx, src/components/__snapshots__/ConfigEditor.test.tsx.snap, src/components/__snapshots__/QueryEditor.test.tsx.snap
This PR updates ConfigEditor and QueryEditor to use `InlineSwitch` and `InlineField` instead of `LegacyForms.Switch`.
=> ENH: update components to use InlineSwitch and InlineField instead of LegacyForms.Switch

src/DataSource.ts, src/responseParse.ts, src/specs/datasource.test.ts, src/streamQuery.ts, src/types.ts
This PR fixes the initial capacity for stream queries. The initial capacity will be greater than maxDataPoints if the capacity is not explicitly defined.
=> ENH: fix initial capacity for stream queries

pkg/archiverappliance/aaclient.go, pkg/archiverappliance/query.go, pkg/archiverappliance/query_test.go, pkg/datasource.go, pkg/models/models.go
The plugin ran multiple queries concurrently with goroutine by itself. This PR fixes to use concurrent.QueryData that is provided by Grafana backend plugin SDK version 0.232.0 and later instead.
=> ENH: use concurrent.QueryData to run queries concurrently

src/components/ConfigEditor.tsx, src/components/Functions.tsx, src/components/QueryEditor.tsx
This PR removes the appearance of gf-form in the QueryEditor. The plugin uses grafana-ui components instead. The functions are wrapped by this PR. Some minor fixes are also included.
=> ENH: remove gf-form appearances in QueryEditor

pkg/archiverappliance/pbparse.go, pkg/archiverappliance/pbparse_test.go, pkg/models/enums.go, pkg/models/functions.go, pkg/models/singledata_test.go, pkg/models/testhelpers.go, src/aafunc.ts
This PR adds the `SEVR as Enum` and `STAT as Enum` options to the `fieldName` function.
The example of displays are as follows. Enum data can be displayed as text such as `NO_ALARM`.
=> ENH: add enum response to the fieldName function for SEVR and STAT

pkg/archiverappliance/query_test.go, pkg/models/arrays.go, pkg/models/enums.go, pkg/models/scalars.go, pkg/models/singledata_test.go, pkg/models/strings.go
Source code of `field_config` for Grafana fields says that `DisplayName` should not be used from a data source. Use `DisplayNameFromDS` instead.
=> MAINT: fix to use DisplayNameFromDS

src/DataSource.ts, src/specs/datasource.test.ts
The frontend passed queries to Go backend even if the PV name is empty.
This PR fixes to pass filtered queries.
=> BUG: pass filtered queries to Go backend

pkg/archiverappliance/pbparse.go, pkg/archiverappliance/pbparse_test.go
As mentioned previously (#102), the Archiver Appliance returns an empty response. This PR fixes the PB parser to handle an empty response.
=> BUG: fix to handle an empty response in pb parser

package.json, src/components/ConfigEditor.tsx, src/components/FunctionParam.tsx, src/components/QueryEditor.tsx, src/components/toSelectableValue.ts, src/components/utils.ts, src/plugin.json, yarn.lock
Select[1] and DataSourceHttpSettings[2] are deprecated UI components.
This PR migrates from the deprecated components to the supported components.
[1] [11.6.x to 12.0.x | Grafana Plugin Tools](https://grafana.com/developers/plugin-tools/migration-guides/update-from-grafana-versions/migrate-11_6_x-to-12_0_x#migrate-from-select-to-combobox)
[2] [Migrating from DataSourceHttpSettings component](https://github.com/grafana/plugin-ui/blob/8c40b12c21f8dd01bc1840804ecf4536009429cd/src/components/ConfigEditor/migrating-from-datasource-http-settings.md)
=> DEP: migrate from deprecated UI components
