sasaki77/archiverappliance-datasource

src/DataSource.ts, src/aafunc.ts, src/components/__snapshots__/FunctionAdd.test.tsx.snap, src/dataProcessor.ts, src/specs/aafunc.test.ts
Add below functions into Sort category.
- sortAvg
- sortMax
- sortMin
- sortSum
- sortAbsMax
- sortAbsMin
=> Add AggFuncs sort functions

docs/query.md, docs/releases.md, src/DataSource.ts, src/specs/datasource.test.ts, src/types.ts
`last` operator allows to retrieve the last data in the specified time range.
=> Add last operator

src/DataSource.ts, src/aafunc.ts, src/components/__snapshots__/FunctionAdd.test.tsx.snap, src/specs/aafunc.test.ts
This PR adds a function to disable the extrapolation for raw operator.
=> Add disableExtrapol function

src/DataSource.ts, src/specs/datasource.test.ts
This PR adds data source test called from Grafana datasource configuration.
=> Fix testDatasource for datasource test

src/aafunc.ts, src/components/__snapshots__/FunctionAdd.test.tsx.snap, src/dataProcessor.ts, src/specs/aafunc.test.ts
This PR adds `movingAverage` function.
=> Add movingAverage function

src/DataSource.ts, src/specs/datasource.test.ts
This commit improves data retrieving from Archiver Appliance.
Requests for same URL is merged per panel.
Therefore, the plugin issues request once for each URLs.
=> Fix query processing to retrieve data efficiently

README.md, src/plugin.json
This PR updates README.md and `plugin.json`.
`plugin.json` can be linting and auto-completion.
=> Update README.md and plugin.json

package.json, src/DataSource.ts, src/aafunc.ts, src/components/FunctionAdd.tsx, src/components/FunctionEditor.tsx, src/components/FunctionParam.tsx, src/components/QueryEditor.test.tsx, src/components/QueryEditor.tsx, src/components/__snapshots__/QueryEditor.test.tsx.snap, src/dataProcessor.ts, src/plugin.json, src/specs/aafunc.test.ts, src/specs/datasource.test.ts, src/types.ts, yarn.lock
This PR adds stream feature. It allows to continuously retrieve archived data. The retrieved data with stream is difference from last update time. So, we can reduce network traffics and process load.
=> Add stream feature

src/components/Functions.tsx, src/components/QueryEditor.tsx, src/components/__snapshots__/Functions.test.tsx.snap, src/components/__snapshots__/QueryEditor.test.tsx.snap
This PR adds help text for the query fields.
The stream forms are moved next to Operator.
=> Update query editor

src/aafunc.ts, src/specs/datasource.test.ts
Hello, 
In order to import this plugin into the backend plugin, there's a few import paths that I'm looking to change to relative paths.
I'd be happy to discuss it if there are concerns.
=> Use relative paths to allow for importing

src/specs/datasource.test.ts
This PR fixes tests for stream.
=> Fix stream test time

src/DataSource.ts, src/components/ConfigEditor.tsx, src/components/__snapshots__/ConfigEditor.test.tsx.snap, src/specs/aafunc.test.ts, src/specs/datasource.test.ts, src/types.ts
This PR adds Use Backend button in configuration.
We can enable the backend for data visualization.
=> Add Use Backend button in configuration

pkg/functions.go, pkg/functions_test.go
=> BUG: Backend delta faulted on 1-length datasets.

src/DataSource.ts, src/specs/datasource.test.ts, src/specs/utils.test.ts, src/utils.ts
Import #47 enhancements into the Typescript data source.
=> Support  PV name with recursive alternation

pkg/archiver-functions.go, pkg/archiver-functions_test.go, pkg/archiver-interface.go, pkg/archiver-query.go, pkg/archiver-query_test.go, pkg/functions_test.go, pkg/test_helpers.go
The PR implements the data extrapolation features that the frontend has when using the "raw" operator. Like the frontend, it also abides by the "disableExtrapol" option in the functions menu.
=> Extrapolation for visualization using the backend

pkg/archiver-query.go, pkg/archiver-query_test.go
This PR fixes #59.
@n-wbrown Could you check the changes? I'll merge after you approve.
=> Fix dataframe name from response to PV name

pkg/archiver-query.go
=> Add pvname label to timeseries dataframe for multi-dimensional alerting

.github/workflows/build-and-test.yml, .github/workflows/publish-release.yml
=> BLD: Update nodeJS version for CI

pkg/archiver-interface.go, pkg/archiver-query.go, pkg/models.go, pkg/query-operators_test.go
=> MAINT: Refactoring Go backend

src/DataSource.ts
This PR enables use hide button with Backend.
=> BUG: Backend don't show hidden target

pkg/archiver-interface.go, pkg/archiver-query.go, pkg/archiver-query_test.go, pkg/models.go
This PR adds alias feature for the backend.
=> ENH: add alias feature for backend

src/DataSource.ts
This PR supports template variables in Backend.
=> ENH: support template variables in Backend

go.mod, go.sum, pkg/functions_handler.go, pkg/functions_handler_test.go, pkg/models.go, pkg/query.go
This PR adds `Array to Scalar` functions in Backend.
=> ENH: add Array to Scalar functions in Backend

pkg/archiverappliance/aaclient.go, pkg/archiverappliance/aaclient_test.go, pkg/models/singledata.go, pkg/models/singledata_test.go
=> BUG: fix to handle empty array response

pkg/archiverappliance/aaclient.go, pkg/archiverappliance/aaclient_test.go, pkg/archiverappliance/query_test.go, pkg/models/models.go, pkg/models/singledata_test.go, pkg/models/strings.go, pkg/models/testhelpers.go, pkg/test_data/string_value_response.JSON
=> BUG: handling string value data

src/components/QueryEditor.tsx, src/components/__snapshots__/QueryEditor.test.tsx.snap
=> Fix the alias pattern label so that it appears as just Pattern

src/components/FunctionParam.tsx, src/components/QueryEditor.tsx
=> BUG: Operator and function parameters with options can't set custom value

src/components/QueryEditor.tsx
Forgot using inputValue in #142.
=> BUG: use inputValue in operator select input

pkg/archiverappliance/aaclient_test.go, pkg/archiverappliance/operators.go, pkg/archiverappliance/operators_test.go, pkg/archiverappliance/query.go, pkg/archiverappliance/query_test.go, pkg/datasource.go, pkg/models/models.go, pkg/models/models_test.go, src/DataSource.ts, src/aaclient.ts, src/components/ConfigEditor.tsx, src/components/QueryEditor.tsx, src/components/__snapshots__/ConfigEditor.test.tsx.snap, src/specs/datasource.test.ts, src/types.ts
This PR fixes #143.
@slacAWallace Could you check that you can set the default operator as you expected?
=> ENH: add the default operator to the data source settings

pkg/models/arrays.go, pkg/models/models.go, pkg/models/singledata_test.go, src/responseParse.ts, src/specs/datasource.test.ts
This PR fixes the time of index array format to local time of server.
=> ENH: fix to use local time for index array format

docs/functions.md, pkg/archiverappliance/aaclient.go, pkg/archiverappliance/error.go, pkg/archiverappliance/query.go, pkg/archiverappliance/query_test.go, pkg/models/functions.go, pkg/models/models.go, src/aafunc.ts
=> ENH: add ignoreEmptyErr function

src/responseParse.ts, src/specs/datasource.test.ts, src/streamQuery.ts
Extrapolation was disabled when stream was enabled. However, data without extrapolation cannot be displayed if there is no data in the data range. Therefore, the plugin is fixed to use extrapolation even if stream is enabled with margin.
=> BUG: fix extrapolation for stream with raw operation

pkg/archiverappliance/aaclient.go, pkg/archiverappliance/aaclient_test.go, pkg/archiverappliance/error.go
This PR fixes a data retrieval from AA to return an error if a http status code is not 200.
=> BUG: fix to return error if a http status code is not 200
